<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Dear {{ $title }}. {{ ucfirst($fullname) }}, </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Your registration has been received. Please save this email for future reference.</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Event:</span> <strong><span style="font-size: 12pt; font-family: Cambria, serif;">The 11th International Workshop on Advanced Materials Science and Nanotechnology (IWAMSN 2024)</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Date: </span><strong>September </strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;"></span></strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;">22 - 25</span></strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;">, 2024</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Venue: </span><strong>Da Nang City, Vietnam</strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">Registration Details:</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Full name: {{ $title }}. {{ $fullname }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Affiliation: {{ $affiliation }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Country: {{ $country }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Registration No.: {{ $guest_code }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Email: {{ $email }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">Conference fee:</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Conference type: {{ $conference_type }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Total amount: {{ $total }}</span><span style="font-size: 12pt; font-family: Cambria, serif;"></span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Payment type: Online Payment</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Payment status: {{ $payment_status }}</span><span style="font-size: 12pt; font-family: Cambria, serif;"></span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">If you need any further assistance, please feel free to contact us at </span><a href="mailto:iwamsn2024@ims.vast.ac.vn" style="font-family: 'Times New Roman', serif; font-size: 13pt; color: blue;"><span style="font-size: 11pt; line-height: 19.8px; font-family: Montserrat;">iwamsn2024@ims.vast.ac.vn</span></a></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">We look forward to seeing you in Danang City!</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Kind regards,</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">IWAMSN 2024 Secretariat Team</span></strong></p>