<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Dear {{ $title }}. {{ ucfirst($fullname) }},</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Your registration has been received. Please save this email for future reference.</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Event:</span> <strong><span style="font-size: 12pt; font-family: Cambria, serif;">The 10th International Workshop on Advanced Materials Science and Nanotechnology (IWAMSN 2024)</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Date: <strong>November </strong></span><strong><span style="font-size: 12pt; font-family: Cambria, serif;">     </span></strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;"> - </span></strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;">     </span></strong><strong><span style="font-size: 12pt; font-family: Cambria, serif;">, 2020</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Venue: <strong>Pullman Danang Beach Resort – 101 Vo Nguyen Giap Str., Da Nang, Viet Nam</strong></span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">Registration Details:</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Full name: {{ $title }}. {{ ucfirst($fullname) }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Registration No.: {{ $guest_code }}</span><span style="font-size: 12pt; font-family: Cambria, serif;">     </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Phone: {{ $mobiphone }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Email: {{ $email }}</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">Conference fee:</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Conference type: {{ $conference_type }}</span><span style="font-size: 12pt; font-family: Cambria, serif;">     </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Total amount: ${{ $total }}</span><span style="font-size: 12pt; font-family: Cambria, serif;">     </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Payment type: Bank transfer</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">Please send proof of bank transfer to </span></strong><a name="Text23"></a>     <strong><span style="font-size: 12pt; font-family: Cambria, serif;">. Receipt will be sent to you after payment completion.</span></strong></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">We look forward to seeing you in Danang!</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;"> </span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 12pt; font-family: Cambria, serif;">Kind regards,</span></p>
<p class="MsoNormal" style="margin: 3pt 0in; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-size: 12pt; font-family: Cambria, serif;">IWAMSN 2024 Organizers</span></strong></p>